version: '3.8'

services:
  spring-test:
    build:
      context: ./spring
      dockerfile: Dockerfile.test
    volumes:
      - ./spring-test-results:/workspace/app/target/site/jacoco
  python-test:
    build: ./scraper
    command: pytest test_scraper.py
    environment:
      - DB_ADDRESS=localhost
      - DB_DATABASE=testdb
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_PORT=3306
